### PR TITLE
Fix [GitHub] token handling

### LINKED ISSUE #2728: Crash in modified GitHub auth
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

Post deploy of #1205:

```
Error: Vendor hook error:,Error: usesRemaining must be an integer
    at Token.update (/home/m/shields/lib/token-pool.js:65:13)
    at GithubApiProvider.updateToken (/home/m/shields/services/github/github-api-provider.js:57:11)
    at request (/home/m/shields/services/github/github-api-provider.js:109:16)
    at Request.request [as _callback] (/home/m/shields/lib/request-handler.js:182:9)
    at Request.self.callback (/home/m/shields/node_modules/request/request.js:185:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/m/shields/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/m/shields/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

### PR DESCRIPTION
**Pull request by paulmelnikow**
Fix #2728 

I'm pretty happy with this fix and it seems to work, though I may want to give this a second look tomorrow with fresher eyes.

### CODE REVIEW

File: services/github/github-api-provider.integration.js [hunk 1]
```diff
@@ -4,70 +4,98 @@ const { expect } = require('chai')
 const serverSecrets = require('../../lib/server-secrets')
 const GithubApiProvider = require('./github-api-provider')
 
-describe('Github API provider with token pool', function() {
+describe('Github API provider', function() {
```
Comment (paulmelnikow) [inline services/github/github-api-provider.integration.js]: This diff is gnarly, though the effect was moving the old text into a `context` and adding a second `context` for the  global token / `{ withPooling: false }` version.

File: services/github/github-api-provider.js [hunk 2]
```diff
@@ -1,6 +1,16 @@
...
 const { TokenPool } = require('../../lib/token-pool')
+const { nonNegativeInteger } = require('../validators')
+
+const headerSchema = Joi.object({
+  'x-ratelimit-limit': nonNegativeInteger,
+  'x-ratelimit-remaining': nonNegativeInteger,
+  'x-ratelimit-reset': nonNegativeInteger,
+})
+  .required()
+  .unknown(true)
```
Comment (calebcartwright) [inline services/github/github-api-provider.js]: This is another new Joi feature for me (have been reading https://github.com/hapijs/joi/blob/v14.3.1/API.md#objectunknownallow). I take it this allows for unknown keys, but does this mean that there are keys we don't know about but want to have available on the object?

File: services/github/github-api-provider.js [hunk 3]
```diff
@@ -63,13 +93,7 @@ class GithubApiProvider {
   }
 
   tokenForUrl(url) {
-    const { globalToken } = this
-    if (globalToken) {
```
Comment (calebcartwright) [inline services/github/github-api-provider.js]: ~~Does this change mean that we'll always use a token from the pool here, even if the global token was set?~~

I see this check still exists but has shifted down below, scratch this!

File: services/github/github-api-provider.js (hunk 2 above)
Comment (paulmelnikow) [reply services/github/github-api-provider.js]: Without `.unknown(true)` this always fails because there are a lot of other headers in the response.

This is where we invoke `Joi.validate` via `BaseService#_request`:

https://github.com/badges/shields/blob/c4efdc8e66ec47250a7e90e666ff312abe226db6/lib/validate.js#L21-L24

`stripUnknown` means keys that aren't in the schema get stripped out, which is nice for the services because it means you can't accidentally use anything that hasn't been validated.

It's not clear whether we can pass that option here.

Comment (calebcartwright) [reply services/github/github-api-provider.js]: Ahhh okay, thanks!

**Comment by calebcartwright** [comment]
Not directly related to this PR but adding here, there was a ton of Github service test failures in the last daily test run: https://circleci.com/gh/badges/daily-tests/78, all seemingly timeout related 

Do we have any idea why they're failing (I can also open a new issue if preferable)

**Comment by paulmelnikow** [comment]
It's related; should be fixed by this. The errors aren't captured in the test summary, but you can see them in the log:

```
0111155457 Vendor hook error: TypeError: token.update is not a function
    at GithubApiProvider.updateToken (/home/circleci/project/shields/services/github/github-api-provider.js:4:1688)
    at request (/home/circleci/project/shields/services/github/github-api-provider.js:10:823)
    at Request.request [as _callback] (/home/circleci/project/shields/lib/request-handler.js:40:311)
    at Request.self.callback (/home/circleci/project/shields/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/circleci/project/shields/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/circleci/project/shields/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

**Comment by paulmelnikow** [comment]
This isn't perfect, but I _think_ it is okay for the moment. I'm eager to get the release blocker cleared. I opened #2733 to discuss what I think could be improved here.
