### PR TITLE
[SourceForge] Fixes, tests and cleaning up

### LINKED ISSUE #1610: Crash in sourceforge
https://sentry.io/shields/shields/issues/503545467/

```
Error: Vendor hook error:,TypeError: Cannot read property 'toISOString' of undefined
    at Object.handler (/home/m/shields/server.js:5541:41)
    at Domain.vendorDomain.run (/home/m/shields/lib/request-handler.js:183:22)
    at Domain.run (domain.js:317:14)
    at /home/m/shields/lib/request-handler.js:182:18
    at gotQueries (/home/m/shields/node_modules/camp/lib/camp.js:910:7)
    at getQueries (/home/m/shields/node_modules/camp/lib/camp.js:241:5)
    at catchpath (/home/m/shields/node_modules/camp/lib/camp.js:903:3)
    at Array.routeLayer (/home/m/shields/node_modules/camp/lib/camp.js:865:7)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.pathLayer (/home/m/shields/node_modules/camp/lib/camp.js:838:16)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.eventSourceLayer (/home/m/shields/node_modules/camp/lib/camp.js:617:49)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.ajaxLayer (/home/m/shields/node_modules/camp/lib/camp.js:517:39)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.wsLayer (/home/m/shields/node_modules/camp/lib/camp.js:506:50)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.genericLayer (/home/m/shields/node_modules/camp/lib/camp.js:444:5)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.monitorHandler (/home/m/shields/lib/sys/monitor.js:46:5)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at listener (/home/m/shields/node_modules/camp/lib/camp.js:401:3)
    at SecureCamp.<anonymous> (/home/m/shields/node_modules/camp/lib/camp.js:364:45)
    at SecureCamp.emit (events.js:160:13)
    at parserOnIncoming (_http_server.js:618:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
  File "/home/m/shields/server.js", line 5541, in Object.handler
    apiUrl += '?start_date=' + start_date.toISOString().slice(0,10) + '&end_date=' + end_date.toISOString().slice(0,10);
  File "/home/m/shields/lib/request-handler.js", line 183, in Domain.vendorDomain.run
    handlerOptions.handler(filteredQueryParams, match, function sendBadge(format, badgeData) {
  File "/home/m/shields/lib/request-handler.js", line 182, in null.<anonymous>
    vendorDomain.run(() => {
  File "/home/m/shields/lib/sys/monitor.js", line 46, in Array.monitorHandler
    next();
  File "/home/m/shields/lib/log.js", line 36, in Function.error
    Raven.captureException(msg, function (sendErr) {
...
(34 additional frame(s) were not displayed)

Error: Vendor hook error:,TypeError: Cannot read property 'toISOString' of undefined
    at Object.handler (/home/m/shields/server.js:5541:41)
    at Domain.vendorDomain.run (/home/m/shields/lib/request-handler.js:183:22)
    at Domain.run (domain.js:317:14)
    at /home/m/shields/lib/request-handler.js:182:18
    at gotQueries (/home/m/shields/node_modules/camp/lib/camp.js:910:7)
    at getQueries (/home/m/shields/node_modules/camp/lib/camp.js:241:5)
    at catchpath (/home/m/shields/node_modules/camp/lib/camp.js:903:3)
    at Array.routeLayer (/home/m/shields/node_modules/camp/lib/camp.js:865:7)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.pathLayer (/home/m/shields/node_modules/camp/lib/camp.js:838:16)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.eventSourceLayer (/home/m/shields/node_modules/camp/lib/camp.js:617:49)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.ajaxLayer (/home/m/shields/node_modules/camp/lib/camp.js:517:39)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.wsLayer (/home/m/shields/node_modules/camp/lib/camp.js:506:50)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.genericLayer (/home/m/shields/node_modules/camp/lib/camp.js:444:5)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.monitorHandler (/home/m/shields/lib/sys/monitor.js:46:5)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at listener (/home/m/shields/node_modules/camp/lib/camp.js:401:3)
    at SecureCamp.<anonymous> (/home/m/shields/node_modules/camp/lib/camp.js:364:45)
    at SecureCamp.emit (events.js:160:13)
    at parserOnIncoming (_http_server.js:618:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
```

### PR DESCRIPTION
**Pull request by PyvesB**
This pull request goes through the following tasks:
- narrowing down the regex to only match what the implementation actually supports. I believe this should fix #1610.
- adding some simple tests, which non existent for this service. This should tick one box of the table in #1358.
- performing a small functional change to remove the `/total` in the badge display for total downloads. In addition to being slightly odd, it was inconsistent with what other badges do for total downloads.
- cleaning up the implementation a bit. Nothing too ambitious, but it should help provide a cleaner starting point for #1573.

Looking forward to feedback! 👍

### CODE REVIEW

File: server.js [hunk 1]
```diff
@@ -5500,37 +5500,35 @@ cache(function(data, match, sendBadge, request) {
...
+  const info = match[1];      // eg, 'dm'
+  const project = match[2];   // eg, 'sevenzip`.
+  const folder = match[3];
+  const format = match[4];
+  let apiUrl = 'http://sourceforge.net/projects/' + project + '/files/' + folder + '/stats/json';
+  const badgeData = getBadgeData('sourceforge', data);
+  let time_period, start_date;
+  badgeData.text[0] = getLabel('downloads', data);
+  // get yesterday since today is incomplete
+  const end_date = new Date((new Date()).getTime() - 1000*60*60*24);
```
Comment (paulmelnikow) [inline server.js]: We have `moment` installed. Do you know if it might provide more readable ways to express these values?

File: server.js [hunk 2]
```diff
@@ -5500,37 +5500,35 @@ cache(function(data, match, sendBadge, request) {
 }));
 
 // SourceForge integration.
-camp.route(/^\/sourceforge\/([^/]+)\/([^/]*)\/?(.*).(svg|png|gif|jpg|json)$/,
+camp.route(/^\/sourceforge\/(dt|dm|dw|dd)\/([^/]*)\/?(.*).(svg|png|gif|jpg|json)$/,
```
Comment (paulmelnikow) [inline server.js]: 👍

File: server.js (hunk 1 above)
Comment (PyvesB) [reply server.js]: Done, it does make things more readable! I asserted by adding a temporary log line that the number of downloads returned in the different tests were strictly equal before and after this change.
