### PR TITLE
[badge/dynamic/json] fix colorscheme on error

### LINKED ISSUE #1442: dynamic badge don't change color if file inaccessible or key not existant
As seen in https://github.com/Cockatrice/Magic-Spoiler/pull/193
- It only displays `label | invalid resource` in green for the json file not existing
- It only displays `label | ` in green for a non-existing $key in the linked json (no example in the linked pr)

The badge right side should change the color to highlight a problem.
For the second case it should print an error, too. It looks like it's returning an empty value, but it should say "key not found" for example.

### PR DESCRIPTION
**Pull request by RedSparr0w**
Closes #1442 

All dynamic badges are currently showing `brightgreen` on right hand side even on error.

This PR causes the right hand side to be `red` if no uri specified or `lightgrey` on other errors.
This also adds an error if the jsonpath/`?query` returns an empty array `no result`

**Notes:**
Was failing due to trying to set `colorB = 'lightgrey'` instead of `colorB = '#9f9f9f'`
Also tried using `colorscheme = 'lightgrey'` but that didn't work due to the users color choice always taking priority and the user needing to specify `?colorB=10ADED` for any color other than brightgreen

### CODE REVIEW

File: service-tests/json.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ t.create('JSON from uri | with prefix & suffix & label')
 
 t.create('JSON from uri | object doesnt exist')
   .get('.json?uri=https://github.com/badges/shields/raw/master/package.json&query=$.does_not_exist')
-  .expectJSON({ name: 'custom badge', value: '' });
+  .expectJSON({ name: 'custom badge', value: 'no result' });
```
Comment (paulmelnikow) [inline service-tests/json.js]: Want to test the color as well? @platan added a `_shields_test` format which exposes it.

File: server.js [hunk 2]
```diff
@@ -7620,14 +7620,20 @@ cache({
...
           throw 'inaccessible';
 
+        badgeData.colorscheme = 'brightgreen';
+
         switch (type){
           case 'json':
             data = (typeof data == 'object' ? data : JSON.parse(data));
-            badgeData.text[1] = (prefix || '') + jp.query(data, pathExpression).join(', ') + (suffix || '');
+            var jsonpath = jp.query(data, pathExpression);
+            if (!jsonpath.length)
```
Comment (paulmelnikow) [inline server.js]: For fewer surprises, would it be better to use `Array.isArray`?

File: service-tests/json.js (hunk 1 above)
Comment (RedSparr0w) [reply service-tests/json.js]: Nice, did not realise this was a thing!
Will update the tests

File: server.js (hunk 2 above)
Comment (RedSparr0w) [reply server.js]: From some testing it seems jsonpath will always return an array,
If the query finds nothing, jsonpath will just return an empty array `[]`

examples based on the following json
```javascript
{
  name: 'project',
  version: '1.2.3'
}
```
`?query=` | jsonpath returned
:--: | :--:
`$.version` | `['1.2.3']`
`$.notfound` | `[]`

File: server.js [hunk 3]
```diff
@@ -7606,6 +7606,7 @@ cache({
     var badgeData = getBadgeData('custom badge', query);
 
     if (!query.uri){
+      badgeData.colorB = '#e05d44'; // red
       badgeData.text[1] = 'no uri specified';
```
Comment (paulmelnikow) [inline server.js]: Another option you could consider here is the setBadgeColor helper in badge-data.js. It will let you use named or hex colors interchangeably, discarding colorB if needed.

Comment (RedSparr0w) [reply server.js]: That is the exact function i needed!
Did not realise it also discarded the user override.
