### PR TITLE
handle malformed url [dynamic-json]

### LINKED ISSUE #1779: Dynamic badge sometimes throws URIError
https://sentry.io/shields/shields/issues/579423699/

```
Error: Vendor hook error:,URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Object.handler (/home/m/shields/server.js:7437:25)
    at Domain.vendorDomain.run (/home/m/shields/lib/request-handler.js:187:37)
    at Domain.run (domain.js:317:14)
    at /home/m/shields/lib/request-handler.js:186:18
    at gotQueries (/home/m/shields/node_modules/camp/lib/camp.js:910:7)
    at getQueries (/home/m/shields/node_modules/camp/lib/camp.js:241:5)
    at catchpath (/home/m/shields/node_modules/camp/lib/camp.js:903:3)
    at Array.routeLayer (/home/m/shields/node_modules/camp/lib/camp.js:865:7)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.pathLayer (/home/m/shields/node_modules/camp/lib/camp.js:838:16)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.eventSourceLayer (/home/m/shields/node_modules/camp/lib/camp.js:617:49)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.ajaxLayer (/home/m/shields/node_modules/camp/lib/camp.js:517:39)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.wsLayer (/home/m/shields/node_modules/camp/lib/camp.js:506:50)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.genericLayer (/home/m/shields/node_modules/camp/lib/camp.js:444:5)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.monitorHandler (/home/m/shields/lib/sys/monitor.js:46:5)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at listener (/home/m/shields/node_modules/camp/lib/camp.js:401:3)
    at SecureCamp.<anonymous> (/home/m/shields/node_modules/camp/lib/camp.js:364:45)
    at SecureCamp.emit (events.js:160:13)
    at parserOnIncoming (_http_server.js:618:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
  File "/home/m/shields/server.js", line 7437, in Object.handler
    var url = encodeURI(decodeURIComponent(query.url || query.uri));
  File "/home/m/shields/lib/request-handler.js", line 187, in Domain.vendorDomain.run
    const result = handlerOptions.handler(filteredQueryParams, match, function sendBadge(format, badgeData) {
  File "/home/m/shields/lib/request-handler.js", line 186, in null.<anonymous>
    vendorDomain.run(() => {
  File "/home/m/shields/lib/sys/monitor.js", line 46, in Array.monitorHandler
    next();
  File "/home/m/shields/lib/log.js", line 36, in Function.error
    Raven.captureException(msg, function (sendErr) {
...
(35 additional frame(s) were not displayed)

Error: Vendor hook error:,URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Object.handler (/home/m/shields/server.js:7437:25)
    at Domain.vendorDomain.run (/home/m/shields/lib/request-handler.js:187:37)
    at Domain.run (domain.js:317:14)
    at /home/m/shields/lib/request-handler.js:186:18
    at gotQueries (/home/m/shields/node_modules/camp/lib/camp.js:910:7)
    at getQueries (/home/m/shields/node_modules/camp/lib/camp.js:241:5)
    at catchpath (/home/m/shields/node_modules/camp/lib/camp.js:903:3)
    at Array.routeLayer (/home/m/shields/node_modules/camp/lib/camp.js:865:7)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.pathLayer (/home/m/shields/node_modules/camp/lib/camp.js:838:16)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.eventSourceLayer (/home/m/shields/node_modules/camp/lib/camp.js:617:49)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.ajaxLayer (/home/m/shields/node_modules/camp/lib/camp.js:517:39)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.wsLayer (/home/m/shields/node_modules/camp/lib/camp.js:506:50)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.genericLayer (/home/m/shields/node_modules/camp/lib/camp.js:444:5)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.monitorHandler (/home/m/shields/lib/sys/monitor.js:46:5)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at listener (/home/m/shields/node_modules/camp/lib/camp.js:401:3)
    at SecureCamp.<anonymous> (/home/m/shields/node_modules/camp/lib/camp.js:364:45)
    at SecureCamp.emit (events.js:160:13)
    at parserOnIncoming (_http_server.js:618:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
```

https://github.com/badges/shields/blob/57a1bf2f082be3c0bcef4250f6a5e783a02fc9cf/server.js#L7437

### PR DESCRIPTION
**Pull request by RedSparr0w**
Closes #1779
returns  on error

```javascript
decodeURIComponent('%1') // URI Malformed
decodeURIComponent('%01') // ''
```

### CODE REVIEW

File: server.js [hunk 1]
```diff
@@ -7247,7 +7247,14 @@ cache({
...
       return;
     }
-    var url = encodeURI(decodeURIComponent(query.url || query.uri));
+
+    try {
+      var url = encodeURI(decodeURIComponent(query.url || query.uri));
+    } catch(e){
+      setBadgeColor(badgeData, 'red');
+      badgeData.text[1] = 'malformed url';
+      sendBadge(format, badgeData);
```
Comment (paulmelnikow) [inline server.js]: Looks like this needs a `return`.

Comment (RedSparr0w) [reply server.js]: Nice catch!

**Comment by RedSparr0w** [comment]
Test passing, commits rebased, should be okay for merge now :smile:
