### PR TITLE
Fix [crates] license badge

### LINKED ISSUE #1059: Crates.io license badge is broken
For example: https://img.shields.io/crates/l/clippy.svg

Currently every badge shows "undefined" as the license. It looks like shields.io is referring to `data.crate.license` in the JSON and the license is located at `data.versions[0].license`.

### PR DESCRIPTION
**Pull request by iKevinY**
License data was moved to crate versions in rust-lang/crates.io#803. Closes #1059.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi! Thanks for fixing this. Would love to get this merged. Could you add [a test](https://github.com/badges/shields/blob/master/service-tests/README.md)?

**Comment by iKevinY** [comment]
@paulmelnikow Added a couple tests; let me know if I should make any changes!

File: service-tests/crates.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+const ServiceTester = require('./runner/service-tester');
+
+const t = new ServiceTester({ id: 'crates', title: 'crates.io' });
+module.exports = t;
+
+t.create('license')
+  .get('/l/libc.json')
+  .expectJSONTypes(Joi.object().keys({
+    name: Joi.equal('license'),
+    value: Joi.not('undefined')
```
Comment (paulmelnikow) [inline service-tests/crates.js]: Could you just use `'MIT/Apache-2.0'` as before? Or, if for some reason this package's license is likely to change, choose a different one?

Comment (iKevinY) [reply service-tests/crates.js]: Done! I don't anticipate the license to change, since the dual MIT/Apache-2.0 license is pretty standard across Rust projects, and `libc` is currently the most download crate.

**Comment by iKevinY** [comment]
@paulmelnikow Hmm, I rebased on top of `master`, but it looks like the build is still failing. 😕

**Comment by paulmelnikow** [comment]
That 403 Forbidden error was due to #979, so I restarted the build.

After that, we've got real failures. Those github failures are still there, which need investigation, plus there's a codetally failure, which I reported at #1069. Clearly those are unrelated to this change.

**Comment by paulmelnikow** [comment]
Those github tests are passing on my machine. So the most likely explanation is that they are also related to #979, in a different manifestation, where the rate limit runs out, affecting some of the requests in the middle of the suite, and not others. It's a little odd that some github tests pass afterward, though some of them are mocked, and others might not be subject to rate limits.
