### PR TITLE
fix [Bower] version tests

### LINKED ISSUE #6532: BowerVersion Service Test Failing
:clock11: **When did the problem start?**
A long time ago (months)

:camera: **Live badge**
https://img.shields.io/bower/v/bootstrap

:wrench: **Is the live badge working?**
Nope, not as far as I can tell

:link: **CircleCI link**
https://app.circleci.com/pipelines/github/badges/daily-tests/951/workflows/803a4c67-3d91-40ea-89f3-9e437d2e9ac5/jobs/1849/tests#failed-test-3

:beetle: **Stack trace**

```
ValidationError: message mismatch: "value" with value "no releases" fails to match the required pattern: /^v\d+(\.\d+)?(\.\d+)?$/
    at Object.exports.process (node_modules/joi/lib/errors.js:184:16)
    at Object.internals.entry (node_modules/joi/lib/validator.js:150:26)
    at Object.exports.entry (node_modules/joi/lib/validator.js:27:30)
    at internals.Base.validate (node_modules/joi/lib/base.js:548:26)
    at Object.internals.assert (node_modules/joi/lib/index.js:225:27)
    at Object.attempt (node_modules/joi/lib/index.js:107:26)
    at Function._expectField (core/service-test-runner/icedfrisby-shields.js:73:13)
    at IcedFrisbyNock.<anonymous> (core/service-test-runner/icedfrisby-shields.js:54:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**
Idk at this point. My initial thought was that maybe Bower had finally been shut down :laughing: Seems like the license and pre-release badges are working though so likely an issue with the test target or an API change upstream

### PR DESCRIPTION
**Pull request by calebcartwright**
Fixes #6532

### CODE REVIEW

File: services/bower/bower-base.js [hunk 1]
```diff
@@ -12,16 +12,10 @@ const schema = Joi.object()
...
-      .keys({
-        name: Joi.string().required(),
-      })
-      .allow(null),
-
-    // latest_release_number can be NULL for bower because bower
+    // Keys can be NULL for bower because bower
     // has no registry to enforce any release exists
     latest_release_number: Joi.string().allow(null),
+    latest_stable_release_number: Joi.string().allow(null),
```
Comment (calebcartwright) [inline services/bower/bower-base.js:18]: AFAICT the upstream libraries.io endpoint has changed the structure of the API response which no longer includes a `latest_stable_release` object, but now includes a `latest_stable_release_number` instead

https://libraries.io/api/bower/bootstrap

File: services/bower/bower-version.service.js [hunk 2]
```diff
@@ -32,17 +32,15 @@ class BowerVersion extends BaseBowerService {
...
-    } else {
-      if (data.latest_stable_release) {
-        return renderVersionBadge({ version: data.latest_stable_release.name })
-      }
+    if (!version) {
+      throw new InvalidResponse({ prettyMessage: 'no releases' })
     }
-    throw new InvalidResponse({ prettyMessage: 'no releases' })
+
+    return renderVersionBadge({ version })
```
Comment (calebcartwright) [inline services/bower/bower-version.service.js:43]: Minor refactoring while I was in here. Decided to skip destructuring of the fetched data because the naming conventions in the response would make eslint unhappy and the destructuring+renaming that would've been required to satiate eslint would've caused a hit on readability IMO due to the long key names

File: services/bower/bower-base.js (hunk 1 above)
Comment (PyvesB) [reply services/bower/bower-base.js:18]: It's at least more consistent with the other `latest_release_number`.

**Review by PyvesB — APPROVED** [review]
Changes make sense. 👍🏻
