### PR TITLE
Fix numeric colorB [static githublanguages]

### LINKED ISSUE #2778: Error: Vendor hook error:,TypeError: s.toLowerCase is not a function
https://sentry.io/shields/shields/issues/846279983/?referrer=github_plugin

```
Error: Vendor hook error:,TypeError: s.toLowerCase is not a function
    at isHexColor (/home/m/shields/gh-badges/lib/color.js:24:31)
    at normalizeColor (/home/m/shields/gh-badges/lib/color.js:32:14)
    at makeBadge (/home/m/shields/gh-badges/lib/make-badge.js:168:12)
    at sendBadge (/home/m/shields/lib/request-handler.js:283:25)
    at githubApiProvider.request (/home/m/shields/services/github/github-languages.service.js:138:13)
    at request (/home/m/shields/services/github/github-api-provider.js:144:7)
    at Request.request [as _callback] (/home/m/shields/lib/request-handler.js:216:9)
    at Request.self.callback (/home/m/shields/node_modules/request/request.js:185:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/m/shields/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/m/shields/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  File "/home/m/shields/gh-badges/lib/color.js", line 24, in isHexColor
    return hexColorRegex.test(s.toLowerCase())
  File "/home/m/shields/gh-badges/lib/color.js", line 32, in normalizeColor
    } else if (isHexColor(color)) {
  File "/home/m/shields/gh-badges/lib/make-badge.js", line 168, in makeBadge
    color: normalizeColor(color),
  File "/home/m/shields/lib/request-handler.js", line 283, in sendBadge
    const svg = makeBadge(badgeData)
  File "/home/m/shields/services/github/github-languages.service.js", line 138, in githubApiProvider.request
    sendBadge(format, badgeData)
...
(18 additional frame(s) were not displayed)

Error: Vendor hook error:,TypeError: s.toLowerCase is not a function
    at isHexColor (/home/m/shields/gh-badges/lib/color.js:24:31)
    at normalizeColor (/home/m/shields/gh-badges/lib/color.js:32:14)
    at makeBadge (/home/m/shields/gh-badges/lib/make-badge.js:168:12)
    at sendBadge (/home/m/shields/lib/request-handler.js:283:25)
    at githubApiProvider.request (/home/m/shields/services/github/github-languages.service.js:138:13)
    at request (/home/m/shields/services/github/github-api-provider.js:144:7)
    at Request.request [as _callback] (/home/m/shields/lib/request-handler.js:216:9)
    at Request.self.callback (/home/m/shields/node_modules/request/request.js:185:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/m/shields/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/m/shields/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

### PR DESCRIPTION
**Pull request by paulmelnikow**
Numeric colors weren't properly being handled by `makeBadge` after #2742.

Since this function really does not need to be accepting colors as strings, rather than make the function more lenient to work with Scoutcamp, I coerced the types of the colors on the way in.

Two tests cover the functionality in the modern service. I don't feel strongly that the legacy version needs coverage at this point, though I've added one for the moment on the github languages badge where this manifested.

Fix #2778

### CODE REVIEW

**Comment by calebcartwright** [comment]
All of the badges on our readme are now showing with the brightgreen color wheras many of them were blue before. Is this expected?

**Comment by paulmelnikow** [comment]
Ha!

- Contributors was changed from blue to brightgreen.
- lgtm went from 4 alerts to 1, though that should still be yellow. That looks like a bug though it is a puzzling way to fail…
- I _think_ the others are correct.

**Comment by calebcartwright** [comment]
And the service and previewUrl refactor count badges?

**Comment by calebcartwright** [comment]
Also coverage is still the same at 89% but as of yesterday our coverage badge was still the yellowgreen color, now showing brightgreen

**Comment by paulmelnikow** [comment]
Oh man, we've got a bunch of silent failures here.

```js
  .expectJSONTypes(
    Joi.object({
      name: Joi.string().regex(/^(commits since){1}[\s\S]+$/),
      value: Joi.string().regex(/^\w+$/),
      color: 'blue',
    })
  )
```

Surprisingly this will pass when `color` is missing, which is what `_shields_test` has been emitting when the default color is used. Let's change that…

**Comment by paulmelnikow** [comment]
Opened #2782.

**Comment by paulmelnikow** [comment]
screen shot 2019-01-16 at 2 11 31 pm

File: services/base.js [hunk 1]
```diff
@@ -334,9 +334,15 @@ class BaseService {
       logoColor: overrideLogoColor,
       logoWidth: overrideLogoWidth,
       link: overrideLink,
-      colorA: overrideLabelColor,
-      colorB: overrideColor,
     } = overrides
+    // Scoutcamp converts numeric query params to numbers. Convert them back.
+    let { colorB: overrideColor, colorA: overrideLabelColor } = overrides
+    if (typeof overrideColor === 'number') {
```
Comment (RedSparr0w) [inline services/base.js]: Would it be better to check if ` !== 'string'`? in case Scoutcamp also sends booleans or other types of data?
