### PR TITLE
two fixes for [packagist] schemas

### LINKED ISSUE #7779: Packagist invalid response data for package version, but only on one repo
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I have two packages on packagist that I am using version shields for. I first thought this was some caching issue, but it's been a few days and it's still the same.

On one of the packages it works perfectly, but the second badge gives the invalid response data error.

image
image

Any ideas on what's wrong and how to fix?

### 🔗 Link to the badge

https://img.shields.io/packagist/v/hyde/framework

### 💡 Possible Solution
Edit: Managed to get it to work by adding the flag `?include_prereleases`. Not sure why it works well on the other one without including prereleases.

### PR DESCRIPTION
**Pull request by chris48s**
closes #7779

### CODE REVIEW

File: services/packagist/packagist-base.js [hunk 1]
```diff
@@ -5,9 +5,12 @@ import { isStable, latest } from '../php-version.js'
...
   Joi.object({
     version: Joi.string().required(),
-    require: Joi.object({
-      php: Joi.string(),
-    }),
+    require: Joi.alternatives(
+      Joi.object({
+        php: Joi.string(),
+      }).required(),
+      Joi.string().valid('__unset')
```
Comment (calebcartwright) [inline services/packagist/packagist-base.js:12]: I'm not terribly familiar with the PHP ecosystem, but are there any other well known values we could potentially see here or is `__unset` essentially it based on what we know today?

Comment (calebcartwright) [reply services/packagist/packagist-base.js:12]: I gather adding a live test would probably be overkill, but would it be worth leaving an inline comment with a link to the issue?

**Review by calebcartwright — APPROVED** [review]
lgtm, no objections to merging as is so have approved though left a few inline questions too

File: services/packagist/packagist-base.js (hunk 1 above)
Comment (chris48s) [reply services/packagist/packagist-base.js:12]: Right - having looked at it, we are running the validation on the uncompressed response which is why the `__unset` values are still in there at the point we validate. I misremembered that we had done something like I suggested in https://github.com/badges/shields/pull/6508#issuecomment-855295658 but we never did.
I think I'd like to revisit this code as I don't think what we are doing now is the best solution but I don't think I want to shave this specific yak tonight :cow2: . I'm going to merge this and punt that to an issue.

Comment (chris48s) [reply services/packagist/packagist-base.js:12]: I've written it up in #7783
