### PR TITLE
Improve CTAN error handling and fix non-svg 404 badges

### LINKED ISSUE #921: CTAN license badge is broken
URL `https://img.shields.io/ctan/l/tex.png` produces this: tex

I think the problem is from [ctan](ctan.org). Their API might have changed since you wrote the code for this badge, and it no longer contains copyright information. For instance (stripped to the interesting bit):

~~~sh
$ curl http://www.ctan.org/json/pkg/tex | python -m json.tool
{
    ...
    "copyright": [],
    ...
}
~~~

### PR DESCRIPTION
**Pull request by paulmelnikow**
Fix #921 

I started work today on some vcr-style tests. They send requests to the server, record the responses to vendor requests, and then play the vendor requests back later. The library I'm using is a little buggy. The suite isn't ready for prime time. I'll add tests as I go. Hopefully there will be a meaningful amount of coverage by the time I've gotten the library under control.

I'm very open to input: https://github.com/paulmelnikow/shields-tests

These are the CTAN tests:
https://github.com/paulmelnikow/shields-tests/blob/master/vendor/ctan/spec.js

### CODE REVIEW

**Comment by paulmelnikow** [comment]
After re-reading an old discussion thread (#411) I agree with @espadrine that tests should be geared toward problem detection. I do still want to push responsibility for testing from the reviewer to the contributor. However we can do that more simply than the approach I began to take. In particular we should hold off on vcr-style tests. Opened a discussion thread: #927.

File: server.js [hunk 1]
```diff
@@ -4826,13 +4833,16 @@ cache(function(data, match, sendBadge, request) {
         sendBadge(format, badgeData);
       } else if (info === 'l') {
         var license = data.license;
-        if (license === '') {
-          badgeData.text[1] = 'Unknown';
-        } else {
-          badgeData.text[1] = license;
+        if (license) {
```
Comment (espadrine) [inline server.js]: I'm not a big fan of implicit conversion to booleans in if / for / while statements, given that they can get counter-intuitive. Could you convert it to a check for a list, along with a check for the existence of at least one license?

Comment (paulmelnikow) [inline server.js]: Sure, updated.
