### PR TITLE
fix default style docs for social badges

### LINKED ISSUE #9867: Incorrect default style of "GitHub Repo stars" badge
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The default style of [GitHub Repo stars](https://shields.io/badges/git-hub-repo-stars) badge is stated as `flat`, while it is actually `social`

### 🔗 Link to the badge

| Default style                                                        | Flat style                                                                   | Social style                                                                     |
| -------------------------------------------------------------------- | ---------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| Defautl style | Flat style | Social style |

### 💡 Possible Solution

The default style seems to be overwritten in 04254e5905e04d7ada0b0b27bb8351d54fe18634

### PR DESCRIPTION
**Pull request by chris48s**
closes #9867

follow up from #9859

### CODE REVIEW

File: core/base-service/openapi.js [hunk 1]
```diff
@@ -241,7 +241,9 @@ function category2openapi(category, services) {
           name: 'style',
           in: 'query',
           required: false,
-          description: 'If not specified, the default style is "flat".',
+          description: `If not specified, the default style is "${
```
Comment (PyvesB) [inline core/base-service/openapi.js:244]: Maybe:
```suggestion
          description: `If not specified, the default style for this badge is "${
```

To make sure that users don't assume the default for this common parameter is the same for all badges?

**Review by PyvesB — APPROVED** [review]
Looks good to me - obviously a test had to fail, it would have been too easy otherwise!
