### PR TITLE
[librariesio] Missing try/catch block and tests

### LINKED ISSUE #1621: Crash in librariesio
https://sentry.io/shields/shields/issues/507009653/

```
Error: Vendor hook error:,TypeError: Cannot read property 'filter' of undefined
    at /home/m/shields/server.js:7129:40
    at Request.request [as _callback] (/home/m/shields/lib/request-handler.js:166:9)
    at Request.self.callback (/home/m/shields/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/m/shields/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/m/shields/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  File "/home/m/shields/server.js", line 7129, in null.<anonymous>
    var deprecated = json.dependencies.filter(function(dep) {
  File "/home/m/shields/lib/request-handler.js", line 166, in Request.request [as _callback]
    callback(err, res, body);
  File "/home/m/shields/lib/log.js", line 36, in Function.error
    Raven.captureException(msg, function (sendErr) {
  File "/home/m/shields/lib/request-handler.js", line 32, in Domain.vendorDomain.on.err
    log.error('Vendor hook error:', err.stack);
...
(13 additional frame(s) were not displayed)

Error: Vendor hook error:,TypeError: Cannot read property 'filter' of undefined
    at /home/m/shields/server.js:7129:40
    at Request.request [as _callback] (/home/m/shields/lib/request-handler.js:166:9)
    at Request.self.callback (/home/m/shields/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/m/shields/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/m/shields/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

### PR DESCRIPTION
**Pull request by PyvesB**
This pull request should close #1621 by adding our usual try/catch block. There weren't any tests for this service, so I implemented a simple test suite (one extra box ticked in #1358! 👍 ) and also got rid of the `var` keyword in favour of more appropriate identifiers.

### CODE REVIEW

File: server.js [hunk 1]
```diff
@@ -7062,59 +7062,64 @@ cache(function(data, match, sendBadge, request) {
...
   }
 
-  var options = {method: 'GET', json: true, uri: uri};
-  var badgeData = getBadgeData('dependencies', data);
+  const options = {method: 'GET', json: true, uri: uri};
+  const badgeData = getBadgeData('dependencies', data);
 
   request(options, function(err, res, json) {
-
     if (err || res.statusCode !== 200) {
```
Comment (platan) [inline server.js]: Would you like to improve error handling by using 
https://github.com/badges/shields/blob/e1755df212ff63b8ec43167e67000d1bbecf429d/lib/error-helper.js#L8
in this PR?

Comment (PyvesB) [reply server.js]: Done, thanks for reviewing!
