### PR TITLE
get the tests passing on windows

### LINKED ISSUE #8289: joi library startup issue
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Hi there, I am currently facing an issue when trying to run `npm start`.

Steps to reproduce:
1. Run `npm ci` gives me this error
```
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.

added 2661 packages, and audited 2663 packages in 42s

228 packages are looking for funding
  run `npm fund` for details

51 vulnerabilities (10 moderate, 34 high, 7 critical)
```
2. Run `npm start` gives me this error
```
\shields\node_modules\joi\lib\errors.js:193
        return new exports.ValidationError(message, details, original);
               ^

Error [ValidationError]: {
  "schemaVersion": "0",
  "categories": [
    {
      "id": "build",
      "name": "Build",
      "keywords": [
        "build"
      ]
    },
    {
      "id": "coverage",
      "name": "Code Coverage",
      "keywords": [
        "coverage"
      ]
    },
    {
      "id": "test-results",
      "name": "Test Results",
      "keywords": [
        "tests"
      ]
    },
    {
      "id": "analysis",
      "name": "Analysis",
      "keywords": [
        "analysis"
      ]
    },
    {
      "id": "chat",
      "name": "Chat",
      "keywords": [
        "chat"
      ]
    },
    {
      "id": "dependencies",
      "name": "Dependencies",
      "keywords": [
        "dependencies"
      ]
    },
    {
      "id": "size",
      "name": "Size",
      "keywords": [
        "size"
      ]
    },
    {
      "id": "downloads",
      "name": "Downloads",
      "keywords": [
        "downloads"
      ]
    },
    {
      "id": "funding",
      "name": "Funding",
      "keywords": [
        "funding"
      ]
    },
    {
      "id": "issue-tracking",
      "name": "Issue Tracking",
      "keywords": [
        "issue"
      ]
    },
    {
      "id": "license",
      "name": "License",
      "keywords": [
        "license"
      ]
    },
    {
      "id": "rating",
      "name": "Rating",
      "keywords": [
        "rating"
      ]
    },
    {
      "id": "social",
      "name": "Social",
      "keywords": [
        "social"
      ]
    },
    {
      "id": "version",
      "name": "Version",
      "keywords": [
        "version"
      ]
    },
    {
      "id": "platform-support",
      "name": "Platform & Version Support",
      "keywords": [
        "platform"
      ]
    },
    {
      "id": "monitoring",
      "name": "Monitoring",
      "keywords": [
        "monitoring"
      ]
    },
    {
      "id": "activity",
      "name": "Activity",
      "keywords": [
        "activity"
      ]
    },
    {
      "id": "other",
      "name": "Other",
      "keywords": []
    }
  ],
  "services" [1]: []
}

[1] "services" does not contain 1 required value(s)
    at Object.exports.process (shields\node_modules\joi\lib\errors.js:193:16)
    at Object.internals.entry (shields\node_modules\joi\lib\validator.js:153:26)        
    at Object.exports.entry (shields\node_modules\joi\lib\validator.js:27:30)
    at internals.Base.validate (shields\node_modules\joi\lib\base.js:548:26)
    at Object.internals.assert (shields\node_modules\joi\lib\index.js:225:27)
    at Object.assert (shields\node_modules\joi\lib\index.js:102:19)
    at assertValidServiceDefinitionExport (shields/core/base-service/service-definitions.js:70:7)
    at collectDefinitions (shields/core/base-service/loader.js:89:3)
    at async shields/scripts/export-service-definitions-cli.js:4:23 {
  _original: {
    schemaVersion: '0',
    categories: [
      { id: 'build', name: 'Build', keywords: [ 'build' ] },
      {
        id: 'coverage',
        name: 'Code Coverage',
        keywords: [ 'coverage' ]
      },
      {
        id: 'test-results',
        name: 'Test Results',
        keywords: [ 'tests' ]
      },
      { id: 'analysis', name: 'Analysis', keywords: [ 'analysis' ] },
      { id: 'chat', name: 'Chat', keywords: [ 'chat' ] },
      {
        id: 'dependencies',
        name: 'Dependencies',
        keywords: [ 'dependencies' ]
      },
      { id: 'size', name: 'Size', keywords: [ 'size' ] },
      { id: 'downloads', name: 'Downloads', keywords: [ 'downloads' ] },
      { id: 'funding', name: 'Funding', keywords: [ 'funding' ] },
      {
        id: 'issue-tracking',
        name: 'Issue Tracking',
        keywords: [ 'issue' ]
      },
      { id: 'license', name: 'License', keywords: [ 'license' ] },
      { id: 'rating', name: 'Rating', keywords: [ 'rating' ] },
      { id: 'social', name: 'Social', keywords: [ 'social' ] },
      { id: 'version', name: 'Version', keywords: [ 'version' ] },
      {
        id: 'platform-support',
        name: 'Platform & Version Support',
        keywords: [ 'platform' ]
      },
      {
        id: 'monitoring',
        name: 'Monitoring',
        keywords: [ 'monitoring' ]
      },
      { id: 'activity', name: 'Activity', keywords: [ 'activity' ] },
      { id: 'other', name: 'Other', keywords: [] }
    ],
    services: []
  },
  details: [
    {
      message: '"services" does not contain 1 required value(s)',
      path: [ 'services' ],
      type: 'array.includesRequiredUnknowns',
      context: {
        unknownMisses: 1,
        label: 'services',
        value: [],
        key: 'services'
      }
    }
  ]
}
```

So basically, I am not able to run the development server on my machine. There is this `joi` library that probably causes the issue.

Environment Information:
OS: Windows 11 Pro
NodeJS Version: v16.16.0
NPM Version: v8.11.0

### 🔗 Link to the badge

_No response_

### 💡 Possible Solution

_No response_

### PR DESCRIPTION
**Pull request by chris48s**
closes #8289

Now that we are running on GHA we can pretty easily just run the tests on Windows and we've got tests covering the functionality in #8289

### CODE REVIEW

**Comment by chris48s** [comment]
d313935 includes the fix suggested in https://github.com/badges/shields/issues/8289#issuecomment-1228951077 which gets most of the tests passing. There are still a few more failures I've not looked into yet.

For the moment I've just started with the core tests.

File: lib/svg-helpers.js [hunk 1]
```diff
@@ -1,5 +1,7 @@
 function svg2base64(svg) {
-  return `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`
+  return `data:image/svg+xml;base64,${Buffer.from(svg.trim()).toString(
```
Comment (chris48s) [inline lib/svg-helpers.js:2]: The difference in the logo tests was a `\n` vs `\r\n` issue. I decided that really the best thing to do was just strip any kind of trailing whitspace rather than try to normalise it as any trailing whitspace after the `>` is doing nothing of use anyway.

**Review by calebcartwright — APPROVED** [review]
Nice :+1: and agreed with the changes; line endings are a pain

**Comment by chris48s** [comment]
Cool. It may also be worth running some of the other test suites on Windows as well as linux - these kind of issues could happen in the frontend/package/etc too, but also I'm slightly wary of "build matrix inflation" (for want of a better term). Interested if you have any thoughts on that point..

**Comment by calebcartwright** [comment]
> but also I'm slightly wary of "build matrix inflation" (for want of a better term). Interested if you have any thoughts on that point..

Yeah I know what you mean, and it's especially true in my experience with GHA because of how granularly each leg shows up under the check status view.

I think my main interest for Windows is largely just to give us back a high degree of confidence that contributors on Windows can clone + install, then start the app, I'm much less concerned with having an exhaustive/equal testing suite on Windows
