### PR TITLE
Fix some example and preview URLs

### LINKED ISSUE #1254: Appveyor tests / same link?!
`Appveyor tests` and ` Appveyor tests branch` have the exact same links:
av_tests

### PR DESCRIPTION
**Pull request by paulmelnikow**
Fix #1254.

### CODE REVIEW

File: lib/all-badge-examples.js [hunk 1]
```diff
@@ -1455,7 +1452,7 @@ const allBadgeExamples = [
       },
       {
         title: 'GitHub issue title',
-        previewUri: '/github/issues/detail/title/badges/shields/979.svg',
+        exampleUri: '/github/issues/detail/title/badges/shields/979.svg',
```
Comment (paulmelnikow) [inline lib/all-badge-examples.js]: This badge is really wide. Making omitting `previewUri` prevents the badge from displaying and growing the column too wide.
