### PR TITLE
[CodeClimate] Added missing try-catch block

### LINKED ISSUE #1607: Missing try/catch in codeclimate
https://sentry.io/shields/imgshieldsio/issues/504528524/

```
Error: Vendor hook error:,TypeError: Cannot read property 'attributes' of undefined
    at /home/m/shields/server.js:2733:57
    at Request.request [as _callback] (/home/m/shields/lib/request-handler.js:166:9)
    at Request.self.callback (/home/m/shields/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/m/shields/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/m/shields/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  File "/home/m/shields/server.js", line 2733, in null.<anonymous>
    const percentage = parseFloat(parsedData.data.attributes.ratings[0].measure.value);
  File "/home/m/shields/lib/request-handler.js", line 166, in Request.request [as _callback]
    callback(err, res, body);
  File "/home/m/shields/lib/log.js", line 36, in Function.error
    Raven.captureException(msg, function (sendErr) {
  File "/home/m/shields/lib/request-handler.js", line 32, in Domain.vendorDomain.on.err
    log.error('Vendor hook error:', err.stack);
...
(13 additional frame(s) were not displayed)

Error: Vendor hook error:,TypeError: Cannot read property 'attributes' of undefined
    at /home/m/shields/server.js:2733:57
    at Request.request [as _callback] (/home/m/shields/lib/request-handler.js:166:9)
    at Request.self.callback (/home/m/shields/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/m/shields/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/m/shields/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

### PR DESCRIPTION
**Pull request by PyvesB**
This pull request should resolve #1607. I believe we were missing a try/catch block for the inner API request. It seems that were are kind of duplicating the same try/catch block twice for this service, but I'm unsure how to handle that in a better way. 😉

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Would it be worth adding a test with some incorrectly structured JSON?

**Comment by PyvesB** [comment]
@paulmelnikow I have added two tests, one for incorrectly structured JSON in the outer query and one for the inner query. I had some struggle with the _icedfrisby-nock_, and opened [an issue](https://github.com/paulmelnikow/icedfrisby-nock/issues/3) there.

File: server.js [hunk 1]
```diff
@@ -2716,34 +2716,39 @@ cache(function(data, match, sendBadge, request) {
...
+            badgeData.colorscheme = colorScale([50, 80, 90, 95], ['red', 'yellow', 'yellowgreen', 'green', 'brightgreen'])(percentage);
+          } else if (type === 'maintainability') {
+            const score = parsedData.data.attributes.ratings[0].letter;
+            badgeData.text[1] = score;
+            badgeData.colorscheme = letterScoreColor(score);
+          }
+          sendBadge(format, badgeData);
+        } catch(e) {
+            badgeData.text[1] = 'invalid';
+            sendBadge(format, badgeData);
```
Comment (espadrine) [inline server.js]: If the inner request call throws after its callback parameter returns, it leads to us writing the response twice, but I can't think of a neat solution apart from counting throws.

I guess it is pretty edge-case, huh? ☺
