### PR TITLE
[Codeship] fix status checking regexp & add new statuses

### LINKED ISSUE #1654: Codeship badge return "Build: Unknown"
The [codeship badges](https://img.shields.io/codeship/e7d56d99-e092-4f45-952d-fdd445139c7a.svg) on https://shields.io/ are "returning Build: Unknown", as are the badges I attempted to create for my new codeship tests. 

image

The [codeship api](https://apidocs.codeship.com/v2/authentication/access-and-permissions) seems to indicate that all calls need an access token. Perhaps this requirement was added after the shields.io badge was coded up? 

If codeship cannot be supported, then we should remove it.

### PR DESCRIPTION
**Pull request by mikkabouzu**
We don't need to match the file extension to determine the status.
This should fix #1654 .

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Also note that it seems the status codes in our code may be slightly outdated:
```javascript
        case 'success':
          badgeData.text[1] = 'passing';
          badgeData.colorscheme = 'brightgreen';
          break;
        case 'projectnotfound':
          badgeData.text[1] = 'not found';
          break;
        case 'branchnotfound':
          badgeData.text[1] = 'branch not found';
          break;
        case 'testing':
        case 'waiting':
          badgeData.text[1] = 'pending';
          break;
        case 'error':
          badgeData.text[1] = 'failing';
          badgeData.colorscheme = 'red';
          break;
        case 'stopped':
          badgeData.text[1] = 'not built';
          break;
```
from the [link](https://documentation.codeship.com/general/account/notifications/#webhook) provided by @dennisnewel 
>initiated: newly started build
error: failed builds
success: passed builds
stopped: stopped builds
waiting: waiting builds
ignored: builds ignored because the account is over the monthly build limit
blocked: builds blocked because of excessive resource consumption
infrastructure_failure: builds which failed because of an internal error on the build VM

So i think it might need to be updated to something like:
```javascript
        case 'success':
          badgeData.text[1] = 'passing';
          badgeData.colorscheme = 'brightgreen';
          break;
        case 'projectnotfound':
          badgeData.text[1] = 'not found';
          break;
        case 'branchnotfound':
          badgeData.text[1] = 'branch not found';
          break;
        case 'testing':
        case 'waiting':
        case 'initiated':
          badgeData.text[1] = 'pending';
          break;
        case 'error':
        case 'infrastructure_failure':
          badgeData.text[1] = 'failing';
          badgeData.colorscheme = 'red';
          break;
        case 'stopped':
        case 'ignored':
        case 'blocked':
          badgeData.text[1] = 'not built';
          break;
```

File: server.js [hunk 1]
```diff
@@ -4954,13 +4954,17 @@ cache(function(data, match, sendBadge, request) {
           break;
         case 'testing':
         case 'waiting':
+        case 'initiated':
           badgeData.text[1] = 'pending';
           break;
         case 'error':
+        case 'infrastructure_failure':
```
Comment (RedSparr0w) [inline server.js]: Not sure if we should set this as `error` or `failing`, what do you think is the best text to describe this.

Codeship returns `error` for this status maybe we should follow suit?
image

Comment (mikkabouzu) [reply server.js]: I don't feel the need to add a new status, if there is an error with the build itself, that's a failing build all the same imo.

**Comment by RedSparr0w** [comment]
Thanks for the PR,
Changes look good to me.

Merged!
😄
