### PR TITLE
[vscode-marketplace] Update to be more consistent with other badges

### LINKED ISSUE #1283: Visual Studio Marketplace version badge should be blue like all the other version badges
A version does not have a "success" or "broken" state like builds, it is informational, like licenses. The only other state it can have is in v0.x.x or prereleases, it can be orange as a warning that it is unstable - but it will never be "broken" or "successful".

All version badges follow this pattern:

[npm]()
[GitHub package version]()
[Maven Central]()
[GitHub release]()
[NuGet]()
[PowerShell Gallery]()
[Eclipse Marketplace]()

Except vs marketplace:

[Visual Studio Marketplace]()

### PR DESCRIPTION
**Pull request by RedSparr0w**
### Colors
closes #1283 

Uses `color-formatters.js` to check the correct color

Badge | Current | Updated
:-- | :---: | :---:
Version | image | image
Rating | image | image
Downloads | image | image

_Note: version color was already being checked, but was being overwritten before the badge was sent_

### Tests
not sure how they were previously passing,
Label was being given `?label="Total Installs"` with the quote marks
- Updated label param
- Shortened descriptions
- Updated formatting to be consistent with other tests.

### Rating
Not sure if this should be updated to be consistent with other badges (remove total count from the end)

visual studio | chrome | mozilla
:---: | :---: | :---:
image | chrome webstore rating badge | mozilla rating badge

### CODE REVIEW

File: server.js [hunk 1]
```diff
@@ -5425,36 +5425,32 @@ camp.route(/^\/vscode-marketplace\/(d|v|r)\/(.*)\.(svg|png|gif|jpg|json)$/,
...
             var version = buffer.results[0].extensions[0].versions[0].version;
             badgeData.text[1] = versionText(version);
             badgeData.colorscheme = versionColor(version);
             break;
-          }
         }
-
       } catch (e) {
         badgeData.text[1] = 'invalid';
+      } finally {
```
Comment (PyvesB) [inline server.js]: We don't usually use finally like this for other badges. I'm not saying we shouldn't but if we refactor the code to have less duplication, it may be trickier to do if we aren't consistent everywhere.

**Comment by PyvesB** [comment]
Changes look good to me! 👍 

As far as the rating is concerned, I have no strong opinion regarding the count at the end. If we can get the information in Chrome and Mozilla, it may in fact be useful to add it at the end of those badges? As a side note, I think we should also have the "star" version we have for several other marketplace badges. ;)

**Comment by RedSparr0w** [comment]
Will leave it with the total count at the end,
Good idea will also add the stars option.

**Comment by paulmelnikow** [comment]
Could we land this?

**Comment by RedSparr0w** [comment]
👍 
Should be ready for merge now, if you could please give it a quick lookover @PyvesB / @paulmelnikow

**Comment by PyvesB** [comment]
@RedSparr0w : I'll take a look at it. 😉

**Comment by PyvesB** [comment]
No comments regarding the latest changes. You could change `getBadgeData('vscode-marketplace', data)` to `getBadgeData('rating', data)` and remove the two `badgeData.text[0] = getLabel('rating', data)` statements, but not sure whether it's even worth doing.

By the way, this might sound like a trivial question, but why did you change to `var`s in the switch statement?

**Comment by RedSparr0w** [comment]
>You could change getBadgeData('vscode-marketplace', data) to getBadgeData('rating', data) and remove the two badgeData.text[0] = getLabel('rating', data) statements.

Can't do that unfortunately otherwise if an error is thrown the badge would return  even if you requested some other badge

>why did you change to vars in the switch statement?

Because our lint throws errors if you have `let`s in a switch that doesn't have brackets around it,
not sure the reasoning behind it though.
```javascript
     // Works
      switch (someVar) {
        case 'value': {
          let anotherVar = true;
          break;
        }
     }
     // Throws lint error
      switch (someVar) {
        case 'value': 
          let anotherVar = true;
          break;
     }
```

**Comment by PyvesB** [comment]
Good point for the `getBadgeData('vscode-marketplace', data)`, I had missed the error case!

Hmm... I wonder if `const` would have done the job.

**Comment by RedSparr0w** [comment]
I think it allows `const` & `var` just not `let`.

**Comment by felixfbecker** [comment]
Is this deployed?

**Comment by paulmelnikow** [comment]
It looks like it's not. [This commit](https://github.com/badges/shields/commits/gh-pages) is what's deployed.
