### PR TITLE
[waffle] colorB fixes & Test added

### LINKED ISSUE #1008: Waffle.io badges missing background color
Badges where it displays `0` look fine, but where the count is non-zero, the background color is missing. Examples:

– https://img.shields.io/waffle/label/resin-io/etcher/does%20not%20extist.svg

– https://img.shields.io/waffle/label/resin-io/etcher/in%20progress.svg

Overriding the background color also doesn't appear to work:

– https://img.shields.io/waffle/label/resin-io/etcher/in%20progress.svg?colorB=334455

### PR DESCRIPTION
**Pull request by ritwickdey**
background color (ColorB) fixed.

image

fixes #1008 

**BTW, all test added against fake data**

### CODE REVIEW

File: server.js [hunk 1]
```diff
@@ -6129,7 +6129,7 @@ cache(function(data, match, sendBadge, request) {
       badgeData.text[0] = data.label || ghLabel;
       badgeData.text[1] = '' + count;
       badgeData.colorscheme = null;
-      badgeData.colorB = '#' + (color || '78bdf2');
+      badgeData.colorB =  '#' + (data.colorB || color || '78bdf2');
```
Comment (paulmelnikow) [inline server.js]: This won't work if `colorB` is something like `lightgreen`.

There's a function `makeColor` which you could import from `./lib/badge-data` which would help.

File: service-tests/waffle.js [hunk 2]
```diff
@@ -0,0 +1,58 @@
+const Joi = require('joi');
+const ServiceTester = require('./runner/service-tester');
+
+const t = new ServiceTester({ id: 'waffle', title: 'Waffle.io' });
+module.exports = t;
+
+
+/*
+ALL test against fake data (`fakeData`).
```
Comment (paulmelnikow) [inline service-tests/waffle.js]: How come this approach was taken? The most helpful comments answer that question. 😀 

Is there any reason not to include a live test as well, so if the API changes we find out about the problems first?

File: server.js (hunk 1 above)
Comment (ritwickdey) [reply server.js]: I have changed it. but  is this `?colorB=black`  supported ? 😮

File: service-tests/waffle.js (hunk 2 above)
Comment (ritwickdey) [reply service-tests/waffle.js]: Actually, there  have some simple counting ( using 2 `for`  loop) logic, so I though, It would be nice if I write test (1st one) for that logic. 

Okay, I am changing the 2nd test against live test. :)

File: server.js (hunk 1 above)
Comment (paulmelnikow) [reply server.js]: Haha, you're totally right, it's not. I guess the website badge does, but not the query parameters. There's always more to learn about this project!

**Comment by ritwickdey** [comment]
Thank you for the merging 😄
